### ISSUE TITLE
organisation handling

### ISSUE THREAD

**Issue by wapaAdmin** [wapaAdmin/tww2ag6496#2]
In order to keep the VSA DSS compatibility, I suggest the following organisation treatment:

- All Organisations from AG-64/AG-96 [see here](https://www.ag.ch/media/kanton-aargau/bvu/umwelt-natur/abwasser/siedlungsentwaesserung/organisationstabelle.zip) are also part of the vsa organisations xtf [here](https://vsa.ch/models/organisation/vsa_organisationen_2020_1.xtf), but with a different prefix. 
- The prefix is altered in the views provided by the sql scripts anyway
- On Import, the organisations are ignored. It is expected to load the organisations from VSA
- On Export, all organisations from AG-64/AG-96 are loaded into the intermediate schema as a first step.

**Comment by cymed** [comment]
implemented
