### ISSUE TITLE
separate vsconfig to separate PR on teksi/wastewater

### ISSUE THREAD

**Issue by cymed** [wapaAdmin/tww2ag6496#81]
See https://github.com/teksi/wastewater/pull/399#discussion_r1768572622

**Comment by Philippluca** [comment]
Extracted with https://github.com/teksi/wastewater/pull/399/commits/57a5f3529e7383a54786790dd8a75f1a64bf0b76 and https://github.com/teksi/wastewater/pull/399/commits/9137d3431525d7bbdfc0feecbeff56107a0db050
