### ISSUE TITLE
Relation tww_od.wwtp_stucture does not exist

### ISSUE THREAD

**Issue by drioeagel** [wapaAdmin/tww2ag6496#88]
**Description**
While importing an AG96 file into the database, the following error occurs:

(psycopg2.errors.UndefinedTable) FEHLER:  Relation »tww_od.wwtp_stucture« existiert nicht
LINE 1: INSERT INTO tww_od.wwtp_stucture(
                    ^
QUERY:  INSERT INTO tww_od.wwtp_stucture(
			  obj_id
			, kind
			)VALUES
			(
			  ws_oid
			, 3032 --unbekannt
			)
CONTEXT:  PL/pgSQL-Funktion tww_app.ft_agxx_gepknoten_insert() Zeile 129 bei SQL-Anweisung

**Exact steps to reproduce the behavior:**
1. Go to Import from Interlis 
2. Pass the validation step successfully
3. Proceed with the import

**Expected Behavior**
The data from the AG96 file should be imported into the database without errors

![grafik](https://github.com/user-attachments/assets/d110eecd-0462-4934-9208-da034b98bb99)

****Desktop (please complete the following information):****
 - TWW version TEKSI AGXX
 - QGIS Version3.34.10-Prizren
 - OS

The import process fails due to a missing table, and data is not written into the database.

**Comment by cymed** [comment]
tww_od.wwtp_structure is created here:

https://github.com/wapaAdmin/tww2ag6496/blob/a972bc220cbeee1f07421abde388a50d4b3fe2e2/datamodel/changelogs/0001/03_tww_db_dss.sql#L488

or in TWW 

https://github.com/teksi/wastewater/blob/ee6bfa75d8bdf861294c9f86e56bc6640aac6de3/datamodel/changelogs/0001/03_tww_db_dss.sql#L488

it seems to me that table was dropped at one point

**Comment by drioeagel** [comment]
I downloaded the dump today from here and created a new DB 
https://github.com/teksi/wastewater/actions/runs/11856947447.

**Comment by cymed** [comment]
Did you get an error when loading tww_dev_structure_with_value_lists_agxx?  
wwtp_structure is created in Line 17622
potential problem could be the string replacement in line 10930

**Comment by drioeagel** [comment]
I created a new DB. When importing the dump file into Postgres, no error is displayed.
![grafik](https://github.com/user-attachments/assets/fc2c4795-b9ce-4b9c-930e-934c5c59eb4b)
![grafik](https://github.com/user-attachments/assets/92c7f066-126e-42a0-b9b2-35aae2b4ff11)

The import of the organization table works correctly. However, an error occurs when importing the AG96 file.


I have tried another file and the import works. Apparently my AG96 file is not correct in a way although the validation does not show any errors.

**Comment by cymed** [comment]
OK ich habe den Fehler gesehen: Ich habe einen Tippfehler in der Function (wwtp_stucture statt wwtp_structure).  Ist unter https://github.com/teksi/wastewater/pull/399/commits/7d84e5da0008c57ba952e56f62ec417dc819e3e3 angepasst. Aktuellster Build ist https://github.com/teksi/wastewater/actions/runs/12034391222
